name: Metrics
on:
  # Schedule daily updates
  schedule: [{ cron: "0 0 * * *" }]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_message: "chore: update metrics"
          output_action: commit
          optimize: svg
          experimental_features: --optimize-svg
          config_timezone: Asia/Shanghai
          config_display: columns
          config_output: svg
          base: header
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_stars: yes
